### ISSUE TITLE
Support for linux arm64 musl

### ISSUE THREAD

**Issue by DonJayamanne** [zeromq/zeromq.js#564]
**Is your feature request related to a problem? Please describe.**
It is a feature request.

**Describe the solution you'd like**
Please could this npm package ship with the linux arm64 musl binaries.
Optionally please could someone provide instructions to bulid these binaries.
I have tried to build them myself, however they fail to load with the following error message
```
warn 03:53:53.069: Exception while attempting zmq : Error relocating .../node_modules/zeromq/prebuilds/linux-arm64/node.napi.musl.node: unsupported relocation type 7
```

**Describe alternatives you've considered**
I have tried building the MSUL versions myself, however as mentioned earlier, it fails to load
Here is the docker docker command used to build them

(below is an azure pipeline task)
```
    - task: Bash@3
      displayName: Build
      env:
        CURRENDIR: $(Build.SourcesDirectory)
        DOCKERCMD: apk add --no-cache pkgconfig curl tar python3 make gcc g++ cmake musl-dev && npm i -g pnpm && npm_config_arch=arm64 ARCH=arm64 pnpm install && npm_config_arch=arm64 ARCH=arm64 pnpm run prebuild
      inputs:
        targetType: 'inline'
        workingDirectory: zeromq.js
        script: |
            docker pull node:18-alpine
            docker tag node:18-alpine builder
            docker run --volume $CURRENDIR/zeromq.js:/app --workdir /app --privileged -e ARCH='arm64' -e npm_config_arch='arm64' builder sh -c "$DOCKERCMD"
```
